### PR TITLE
Migrate to Slack SDK v5

### PR DESCRIPTION
**Pull request by pizzacat83**
:tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:
:tada::tada::tada: #️⃣5️⃣ TSG 💨:tada::tada::tada:
:tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:

## Migrate Guidlines Checklist
[Migration Guide](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v5)
### Common
- [x] add library that exports SlackInterface
- [x] rewrite code from importing `@slack/client` to importing ↑ module
- [x] using callback -> use Promise :thinking:
  * grepで探すとかが難しいので全く確かめていないんですが，多分みんなPromise使ってますよね💦
- [x] using `agent` option -> simplify properties
- [x] comparing error codes with string literals -> compare error codes with `ErrorCode.*`
- [x] logger objects -> adjust code

### WebClient
- [x] using metadata `scopes`, `acceptedScopes`, `retryAfter` -> moved to `response_metadata.*`
- [x] using `files.comments.add` `files.comments.edit` -> removed
- [x] using `refreshToken` -> removed
- [x] using `retryPolicies` -> adjust code

### RTMClient
- [x] listening on `raw_message` event -> listen on `slack_events` event

### Packages
- [x] uninstall `@slack/client`

いくつかはチェック済みですが，grepで雑に探してるだけなのでひょっとしたら抜けがあるかもしれません。「いやいやそのメソッドこのbotが使ってるよ」とかがあればコメントしていただけるとありがたいです。

### CODE REVIEW

**Comment by pizzacat83** [comment]
## `@slack/client` 除去チェックリスト
- [x] [`lyrics/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/lyrics/index.ts)
- [x] [`ponpe/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/ponpe/index.ts)
- [x] [`oauth/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/oauth/index.ts)
- [ ] [`achievements/index_production.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/achievements/index_production.ts)
- [x] [`deploy/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/deploy/index.ts)
- [x] [`wordhero/crossword.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/wordhero/crossword.ts)
- [x] [`wordhero/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/wordhero/index.ts)
- [x] [`context-free/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/context-free/index.ts)
- [ ] [`oogiri/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/oogiri/index.ts)
- [ ] [`welcome/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/welcome/index.ts)
- [x] [`better-custom-response/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/better-custom-response/index.ts)
- [x] [`tiobot/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/tiobot/index.ts)
- [x] [`slack-log/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/slack-log/index.ts)
- [ ] [`tunnel/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/tunnel/index.ts)
- [x] [`atcoder/types.d.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/atcoder/types.d.ts)
- [x] [`voiperrobot/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/voiperrobot/index.ts)
- [ ] [`lib/slack.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/lib/slack.ts)
- [ ] [`lib/slackUtils.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/lib/slackUtils.ts)
- [ ] [`scrapbox/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/scrapbox/index.ts)
- [x] [`emoxpand/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/emoxpand/index.ts)
- [x] [`tsglive/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/tsglive/index.ts)
- [x] [`emoji-modifier/index.ts`](https://github.com/tsg-ut/slackbot/blob/a640b9d786bc53adbf01166d86d6d60d8168be4b/emoji-modifier/index.ts)

**Comment by hakatashi** [comment]
@pizzacat83 このブランチ引き継いでいいですか～?

**Comment by pizzacat83** [comment]
おねがいじばず……… zuby

**Comment by hakatashi** [comment]
雑だけどこんな感じでいいんじゃないかな～? とりあえず開発環境で動かしてみて目立ったエラーがないことは確認しました。

**Review by hakatashi — APPROVED** [review]
自分のブランチなのでLGTM

LGTM

**Review by pizzacat83 — COMMENTED** [review]
:ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party::ojigineko-party:

**Pull request merged**
